#############################################################################
# Makefile for building: qtwebengine
# Generated by qmake (3.1) (Qt 5.15.7)
# Project:  qtwebengine.pro
# Template: subdirs
# Command: /usr/lib/qt5/bin/qmake -o Makefile qtwebengine.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qtwebengine1.0.0
DISTDIR = /home/havok/working/qt/qt/qtwebengine/.obj/qtwebengine1.0.0
SUBTARGETS    =  \
		sub-src \
		sub-examples \
		sub-tests


sub-src-qmake_all:  FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2
	cd src/ && $(MAKE) -f Makefile qmake_all
sub-src: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile
sub-src-make_first: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile 
sub-src-all: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile all
sub-src-clean: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile clean
sub-src-distclean: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile distclean
sub-src-install_subtargets: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile install
sub-src-uninstall_subtargets: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile uninstall
sub-examples-qmake_all: sub-src-qmake_all FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2
	cd examples/ && $(MAKE) -f Makefile qmake_all
sub-examples: sub-src FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile
sub-examples-make_first: sub-src-make_first FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile 
sub-examples-all: sub-src-all FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile all
sub-examples-clean: sub-src-clean FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile clean
sub-examples-distclean: sub-src-distclean FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile distclean
sub-examples-install_subtargets: sub-src-install_subtargets FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile install
sub-examples-uninstall_subtargets: sub-src-uninstall_subtargets FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile uninstall
sub-tests-qmake_all: sub-src-qmake_all FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2
	cd tests/ && $(MAKE) -f Makefile qmake_all
sub-tests: sub-src FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile
sub-tests-make_first: sub-src-make_first FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile 
sub-tests-all: sub-src-all FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile all
sub-tests-clean: sub-src-clean FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile clean
sub-tests-distclean: sub-src-distclean FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile distclean
sub-tests-install_subtargets: sub-src-install_subtargets FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile install
sub-tests-uninstall_subtargets: sub-src-uninstall_subtargets FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile uninstall

Makefile: qtwebengine.pro .qmake.conf .qmake.cache /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		mkspecs/modules-inst/qt_lib_pdf.pri \
		mkspecs/modules-inst/qt_lib_pdf_private.pri \
		mkspecs/modules/qt_lib_pdf.pri \
		mkspecs/modules-inst/qt_lib_pdfwidgets.pri \
		mkspecs/modules-inst/qt_lib_pdfwidgets_private.pri \
		mkspecs/modules/qt_lib_pdfwidgets.pri \
		mkspecs/modules-inst/qt_lib_webengine.pri \
		mkspecs/modules-inst/qt_lib_webengine_private.pri \
		mkspecs/modules/qt_lib_webengine.pri \
		mkspecs/modules-inst/qt_lib_webenginecore.pri \
		mkspecs/modules-inst/qt_lib_webenginecore_private.pri \
		mkspecs/modules/qt_lib_webenginecore.pri \
		mkspecs/modules-inst/qt_lib_webenginecoreheaders_private.pri \
		mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		mkspecs/modules-inst/qt_lib_webenginewidgets.pri \
		mkspecs/modules-inst/qt_lib_webenginewidgets_private.pri \
		mkspecs/modules/qt_lib_webenginewidgets.pri \
		mkspecs/modules-inst/qt_plugin_qpdf.pri \
		mkspecs/modules/qt_plugin_qpdf.pri \
		mkspecs/modules-inst/qt_plugin_qwebengineview.pri \
		mkspecs/modules/qt_plugin_qwebengineview.pri \
		mkspecs/modules/qt_tool_qwebengine_convert_dict.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qmodule.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_prefix_build_check.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_build_config.prf \
		.qmake.conf \
		.qmake.cache \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		src/buildtools/config/support.pri \
		mkspecs/features/functions.prf \
		mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/configure_base.prf \
		src/buildtools/config/functions.pri \
		configure.pri \
		config.cache \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_configure.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_parts.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions_off.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_example_installs.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/precompile_header.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/largefile.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_build_extra.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_docs_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		qtwebengine.pro
	$(QMAKE) -o Makefile qtwebengine.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
mkspecs/modules-inst/qt_lib_pdf.pri:
mkspecs/modules-inst/qt_lib_pdf_private.pri:
mkspecs/modules/qt_lib_pdf.pri:
mkspecs/modules-inst/qt_lib_pdfwidgets.pri:
mkspecs/modules-inst/qt_lib_pdfwidgets_private.pri:
mkspecs/modules/qt_lib_pdfwidgets.pri:
mkspecs/modules-inst/qt_lib_webengine.pri:
mkspecs/modules-inst/qt_lib_webengine_private.pri:
mkspecs/modules/qt_lib_webengine.pri:
mkspecs/modules-inst/qt_lib_webenginecore.pri:
mkspecs/modules-inst/qt_lib_webenginecore_private.pri:
mkspecs/modules/qt_lib_webenginecore.pri:
mkspecs/modules-inst/qt_lib_webenginecoreheaders_private.pri:
mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
mkspecs/modules-inst/qt_lib_webenginewidgets.pri:
mkspecs/modules-inst/qt_lib_webenginewidgets_private.pri:
mkspecs/modules/qt_lib_webenginewidgets.pri:
mkspecs/modules-inst/qt_plugin_qpdf.pri:
mkspecs/modules/qt_plugin_qpdf.pri:
mkspecs/modules-inst/qt_plugin_qwebengineview.pri:
mkspecs/modules/qt_plugin_qwebengineview.pri:
mkspecs/modules/qt_tool_qwebengine_convert_dict.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qmodule.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_prefix_build_check.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_build_config.prf:
.qmake.conf:
.qmake.cache:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
src/buildtools/config/support.pri:
mkspecs/features/functions.prf:
mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/configure_base.prf:
src/buildtools/config/functions.pri:
configure.pri:
config.cache:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_configure.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_parts.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions_off.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_example_installs.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/precompile_header.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/largefile.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_build_extra.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_docs_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
qtwebengine.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile qtwebengine.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2

qmake_all: sub-src-qmake_all sub-examples-qmake_all sub-tests-qmake_all FORCE

make_first: sub-src-make_first sub-examples-make_first sub-tests-make_first  FORCE
all: sub-src-all sub-examples-all sub-tests-all  FORCE
clean: sub-src-clean sub-examples-clean sub-tests-clean  FORCE
distclean: sub-src-distclean sub-examples-distclean sub-tests-distclean hostcompiler-distclean webengine-alsa-distclean webengine-freetype-distclean webengine-glibc-distclean webengine-jpeglib-distclean webengine-khr-distclean webengine-libvpx-distclean webengine-libxml2-distclean webengine-re2-distclean webengine-snappy-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.cache config.cache config.log mkspecs/modules/*.pri mkspecs/modules-inst/*.pri .qmake.cache .qmake.stash
install_subtargets: sub-src-install_subtargets sub-examples-install_subtargets FORCE
uninstall_subtargets: sub-src-uninstall_subtargets sub-examples-uninstall_subtargets FORCE

hostcompiler-distclean:
	-cd config.tests/hostcompiler && $(MAKE) distclean

webengine-alsa-distclean:
	-cd config.tests/webengine-alsa && $(MAKE) distclean

webengine-freetype-distclean:
	-cd config.tests/webengine-freetype && $(MAKE) distclean

webengine-glibc-distclean:
	-cd config.tests/webengine-glibc && $(MAKE) distclean

webengine-jpeglib-distclean:
	-cd config.tests/webengine-jpeglib && $(MAKE) distclean

webengine-khr-distclean:
	-cd config.tests/webengine-khr && $(MAKE) distclean

webengine-libvpx-distclean:
	-cd config.tests/webengine-libvpx && $(MAKE) distclean

webengine-libxml2-distclean:
	-cd config.tests/webengine-libxml2 && $(MAKE) distclean

webengine-re2-distclean:
	-cd config.tests/webengine-re2 && $(MAKE) distclean

webengine-snappy-distclean:
	-cd config.tests/webengine-snappy && $(MAKE) distclean

html_docs:
	$(MAKE) -f $(MAKEFILE) prepare_docs && $(MAKE) -f $(MAKEFILE) generate_docs

docs:
	$(MAKE) -f $(MAKEFILE) html_docs && $(MAKE) -f $(MAKEFILE) qch_docs

sub-src-install_html_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile install_html_docs
sub-examples-install_html_docs: sub-src-install_html_docs
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile install_html_docs
sub-tests-install_html_docs: sub-src-install_html_docs
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile install_html_docs
install_html_docs: sub-src-install_html_docs sub-examples-install_html_docs sub-tests-install_html_docs

sub-src-uninstall_html_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile uninstall_html_docs
sub-examples-uninstall_html_docs: sub-src-uninstall_html_docs
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile uninstall_html_docs
sub-tests-uninstall_html_docs: sub-src-uninstall_html_docs
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile uninstall_html_docs
uninstall_html_docs: sub-src-uninstall_html_docs sub-examples-uninstall_html_docs sub-tests-uninstall_html_docs

sub-src-install_qch_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile install_qch_docs
sub-examples-install_qch_docs: sub-src-install_qch_docs
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile install_qch_docs
sub-tests-install_qch_docs: sub-src-install_qch_docs
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile install_qch_docs
install_qch_docs: sub-src-install_qch_docs sub-examples-install_qch_docs sub-tests-install_qch_docs

sub-src-uninstall_qch_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile uninstall_qch_docs
sub-examples-uninstall_qch_docs: sub-src-uninstall_qch_docs
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile uninstall_qch_docs
sub-tests-uninstall_qch_docs: sub-src-uninstall_qch_docs
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile uninstall_qch_docs
uninstall_qch_docs: sub-src-uninstall_qch_docs sub-examples-uninstall_qch_docs sub-tests-uninstall_qch_docs

sub-src-install_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile install_docs
sub-examples-install_docs: sub-src-install_docs
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile install_docs
sub-tests-install_docs: sub-src-install_docs
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile install_docs
install_docs: sub-src-install_docs sub-examples-install_docs sub-tests-install_docs

sub-src-uninstall_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile uninstall_docs
sub-examples-uninstall_docs: sub-src-uninstall_docs
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile uninstall_docs
sub-tests-uninstall_docs: sub-src-uninstall_docs
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile uninstall_docs
uninstall_docs: sub-src-uninstall_docs sub-examples-uninstall_docs sub-tests-uninstall_docs

sub-src-qch_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile qch_docs
sub-examples-qch_docs: sub-src-qch_docs
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile qch_docs
sub-tests-qch_docs: sub-src-qch_docs
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile qch_docs
qch_docs: sub-src-qch_docs sub-examples-qch_docs sub-tests-qch_docs

sub-src-prepare_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile prepare_docs
sub-examples-prepare_docs: sub-src-prepare_docs
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile prepare_docs
sub-tests-prepare_docs: sub-src-prepare_docs
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile prepare_docs
prepare_docs: sub-src-prepare_docs sub-examples-prepare_docs sub-tests-prepare_docs

sub-src-generate_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile generate_docs
sub-examples-generate_docs: sub-src-generate_docs
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile generate_docs
sub-tests-generate_docs: sub-src-generate_docs
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile generate_docs
generate_docs: sub-src-generate_docs sub-examples-generate_docs sub-tests-generate_docs

sub-src-check:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile check
sub-examples-check: sub-src-check
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile check
sub-tests-check: sub-src-check
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile check
check: sub-src-check sub-examples-check sub-tests-check

sub-src-benchmark:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile benchmark
sub-examples-benchmark: sub-src-benchmark
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile benchmark
sub-tests-benchmark: sub-src-benchmark
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -f Makefile benchmark
benchmark: sub-src-benchmark sub-examples-benchmark sub-tests-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: sub-src-distdir sub-examples-distdir sub-tests-distdir FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents mkspecs/modules-inst/qt_lib_pdf.pri mkspecs/modules-inst/qt_lib_pdf_private.pri mkspecs/modules/qt_lib_pdf.pri mkspecs/modules-inst/qt_lib_pdfwidgets.pri mkspecs/modules-inst/qt_lib_pdfwidgets_private.pri mkspecs/modules/qt_lib_pdfwidgets.pri mkspecs/modules-inst/qt_lib_webengine.pri mkspecs/modules-inst/qt_lib_webengine_private.pri mkspecs/modules/qt_lib_webengine.pri mkspecs/modules-inst/qt_lib_webenginecore.pri mkspecs/modules-inst/qt_lib_webenginecore_private.pri mkspecs/modules/qt_lib_webenginecore.pri mkspecs/modules-inst/qt_lib_webenginecoreheaders_private.pri mkspecs/modules/qt_lib_webenginecoreheaders_private.pri mkspecs/modules-inst/qt_lib_webenginewidgets.pri mkspecs/modules-inst/qt_lib_webenginewidgets_private.pri mkspecs/modules/qt_lib_webenginewidgets.pri mkspecs/modules-inst/qt_plugin_qpdf.pri mkspecs/modules/qt_plugin_qpdf.pri mkspecs/modules-inst/qt_plugin_qwebengineview.pri mkspecs/modules/qt_plugin_qwebengineview.pri mkspecs/modules/qt_tool_qwebengine_convert_dict.pri .qmake.conf .qmake.stash src/buildtools/config/support.pri mkspecs/features/functions.prf mkspecs/features/default_pre.prf src/buildtools/config/functions.pri configure.pri config.cache qtwebengine.pro $(DISTDIR)/

sub-src-distdir: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/src/src.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/src

sub-examples-distdir: FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/examples/examples.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/examples

sub-tests-distdir: FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/havok/working/qt/qt/qtwebengine/tests/tests.pro QT_BUILD_PARTS+=tests 'QMAKE_EXTRA_ARGS+=-proprietary-codecs -feature-webengine-system-libvpx -webengine-jumbo-build 0 -system-ffmpeg -system-opus -system-webp -system-webengine-icu -webengine-kerberos' QMAKE_PYTHON2=python2 ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/tests

