usr/share/qt5/resources/qtwebengine_devtools_resources.pak
usr/share/qt5/resources/qtwebengine_resources.pak
usr/share/qt5/resources/qtwebengine_resources_100p.pak
usr/share/qt5/resources/qtwebengine_resources_200p.pak
usr/share/qt5/translations/qtwebengine_locales/*

# Set the WebEngine Hunspell .bdic binary dictionary directory environment variable.
debian/90qtwebengine-dictionaries-path.conf etc/environment.d
